package:
  name: pyncl
  version: !!str 0.1

source:
  path: ../src

requirements:
  build:
    - python>=3.6
    - numpy>=1.17.4

  run:
    - python>=3.6
    - numpy>=1.17.4

test:
  imports:
    - NglLib

