package:
  name: pyncl
  version: !!str 0.1

source:
  path: ../src

requirements:
  build:
    - python
    - pynio
    - pyngl
    - numpy

  run:
    - python
    - pynio
    - pyngl
    - numpy

test:
  imports:
    - NglLib

